### ISSUE TITLE
Cors Issue with Allow Origins

### ISSUE THREAD

**Issue by RiceRiceBaby** [kevinselwyn/fast#3]
Hi. I am trying to run this library and get the following error:
Access to XMLHttpRequest at 'http://api.fast.com/netflix/speedtest?https=true&token=YXNkZmFzZGxmbnNkYWZoYXNkZmhrYWxm&urlCount=3' from origin 'http://www.sample.com/' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin.

The readme says its whitelisted on 8000. The problem is our app needs to run on 8080, 9000, and 9001. Its not allowed to run on 8000. Is there anything I can do to resolve this issue on my side?

**Comment by kevinselwyn** [comment]
This library is really just a wrapper for `http://api.fast.com/netflix/speedtest`. That URL seems to only be accessible via port `8000`, which we have no control over.
